
library(dplyr)
library(tidyverse)
library(data.table)
library(devtools)
library(Biostrings)
library(ggplot2)
library(ggpubr)
library(GenomicRanges)
library(rtracklayer)
library(igraph)
library(seqinr)
library(ape)
library(plotly)
library(tispec) # remotes::install_github("roonysgalbi/tispec")
library(TAF) # for mkdir 
